#!/usr/bin/env python

import argparse
import collections
import operator
import json
import re
import sys
import shlex
import subprocess
import concurrent.futures as cfutures


linemarker = re.compile(r'^#\s(\d+)\s"([^"]+)"((?:\s\d)*)')

def process_file(histogram, content):
    file_stack = []
    for line in content.splitlines():
        m = linemarker.match(line)
        if m:
            filename = m.group(2)
            flags = tuple(map(int, m.group(3).split()))
            if 1 in flags or not flags:
                file_stack.append(filename)
            elif 2 in flags:
                file_stack.pop()
        else:
            histogram[file_stack[-1]] += 1

class QuietBar:
    def __init__(self, msg, max=None):
        pass

    def iter(self, iterator):
        return iterator

try:
    from progress.bar import Bar
except ImportError:
    Bar = QuietBar


def call_preprocessor(args):
    try:
        mode_flag_index = args.index('-c')
    except IndexError:
        return None

    try:
        out_flag_index = args.index('-o')
    except IndexError:
        out_flag_index = None

    res = list(args)
    res[mode_flag_index] = '-E'
    res[out_flag_index + 1] = '-'

    return res


def run(fd, thread_count=1, filter=re.compile('.*'), verbose=False, output='-'):
    compile_commands = json.load(fd)
    with cfutures.ThreadPoolExecutor(max_workers=thread_count) as executor:
        futures_to_file = {}
        RunBar = Bar if verbose else QuietBar
        for compile_command in RunBar('Collecting   ').iter(compile_commands):
            directory = compile_command['directory']
            arguments = compile_command.get('arguments')

            if arguments is None:
                command = compile_command.get('command')
                arguments = shlex.split(command)

            ccfile = compile_command.get('file')
            if ccfile is None:
                raise ValueError("no file key for {}".format(" ".join(arguments)))

            if not filter.match(ccfile):
                continue

            new_arguments = call_preprocessor(arguments)
            if new_arguments is None:
                continue

            future = executor.submit(subprocess.run,
                                     new_arguments,
                                     cwd=directory,
                                     encoding='utf-8',
                                     stderr=subprocess.DEVNULL,
                                     stdout=subprocess.PIPE)
            futures_to_file[future] = ccfile

        histogram = collections.defaultdict(int)
        for future in RunBar('Preprocessing', max=len(futures_to_file)).iter(cfutures.as_completed(futures_to_file)):
            ccfile = futures_to_file[future]
            process = future.result()
            process_file(histogram, process.stdout)
            del futures_to_file[future]
            del future

        if output == '-':
            fd = sys.stdout
        else:
            fd = open(output, "w")

        with fd:
            for k, v in sorted(histogram.items(), key=operator.itemgetter(1), reverse=True):
                fd.write(f'{k} {v}\n')


parser = argparse.ArgumentParser(description='Count preprocessed lines from compile database.')
parser.add_argument('compile_command', type=argparse.FileType('r'), help='JSON compilation database')
parser.add_argument('--filter', metavar='regexp', dest='pattern', type=str,
                    default=r'.*', help='source filter')
parser.add_argument('-j', metavar='N', dest='thread_count', type=int, default=1, help='Spawn N threads')
parser.add_argument('-q', dest='quiet', action='store_true', help='quiet mode')
parser.add_argument('-o', dest='output', type=str, default="-", help='output file')

args = parser.parse_args()

run(args.compile_command,
    args.thread_count, re.compile(args.pattern),
    not args.quiet,
    args.output)




